# Generated by Django 5.2.7 on 2025-10-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs_data', models.JSONField(help_text='JSON com as perguntas e respostas do chat')),
                ('result_data', models.JSONField(blank=True, help_text='JSON com o feedback e cálculo da IA', null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='reports_pdf/')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
