# Generated by Django 5.2.7 on 2025-10-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationreport',
            name='gamma_presentation_url',
            field=models.URLField(blank=True, help_text='URL da apresentação gerada pelo Gamma (se houver)', max_length=500, null=True),
        ),
    ]
